// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB55wIRoqJ9OetM6pfhj0-jTfIGcwDUCVs',
    appId: '1:44513432131:web:9b7a1e0f964ec67b39faf6',
    messagingSenderId: '44513432131',
    projectId: 'pixel13',
    authDomain: 'pixel13.firebaseapp.com',
    storageBucket: 'pixel13.appspot.com',
    measurementId: 'G-Z0CG8ZYE9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-YdZLQVR5QVdUvCqRriWuImbl5pV3rvY',
    appId: '1:44513432131:android:a48eb9b6c2dfbdee39faf6',
    messagingSenderId: '44513432131',
    projectId: 'pixel13',
    storageBucket: 'pixel13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpBy44J-jZpg5VGL-s2X7bh0GKerPre4Y',
    appId: '1:44513432131:ios:a87ecff231d4b82d39faf6',
    messagingSenderId: '44513432131',
    projectId: 'pixel13',
    storageBucket: 'pixel13.appspot.com',
    iosClientId: '44513432131-cme09jkgl0m96cba467lesr9t8c9pe0v.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpBy44J-jZpg5VGL-s2X7bh0GKerPre4Y',
    appId: '1:44513432131:ios:a87ecff231d4b82d39faf6',
    messagingSenderId: '44513432131',
    projectId: 'pixel13',
    storageBucket: 'pixel13.appspot.com',
    iosClientId: '44513432131-cme09jkgl0m96cba467lesr9t8c9pe0v.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
